import os

# Filesystem-related constants
BASE_DIR = os.path.dirname(__file__)

# General game constants
FPS = 30
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
TILE_SIZE = 40  # pixels
assert SCREEN_WIDTH % TILE_SIZE == 0, "TILE_SIZE does not divide SCREEN_WIDTH"
assert SCREEN_HEIGHT % TILE_SIZE == 0, "TILE_SIZE does not divide SCREEN_HEIGHT"
MAP_WIDTH, MAP_HEIGHT = SCREEN_WIDTH//TILE_SIZE, SCREEN_HEIGHT//TILE_SIZE
MAP_SIZE = (MAP_WIDTH, MAP_HEIGHT)